version: '3.8'
services:
  crud-test:
    build: .
    container_name: crud-test
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
    ports:
      - '8000:8081'
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5000:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
