spring:

  datasource:
    url: jdbc:postgresql://db:5432/mydb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

springdoc:
  swagger-ui:
    use-root-path: true
